### ISSUE TITLE
Phone doesn't destroy Keypad properly

### ISSUE THREAD

**Issue by DammitStella** [Exho1/gPhone#12]
https://gfycat.com/DismalElatedHarpseal
Steps to reproduce: Get called, Accept, close the phone and open it again. The keypad stays.

**Comment by Exho1** [comment]
I've encountered this before, the phone should jump to the homescreen (to remove all app panels) and then hide itself, it appears that is not working correctly

**Comment by MStruntze** [comment]
This also seems to happen after winning Flappy Garry and then closing the phone (with g)
![persistentpanel](https://cloud.githubusercontent.com/assets/638047/6998956/8a6d9f30-dbf3-11e4-9e5f-ca4bb5eb6fb6.PNG)

**Comment by Exho1** [comment]
MStruntze, I was unable to replicate your issue in my testing. I closed the phone as Garry's face was enlarging and then tried again this time after he had finished.

**Comment by MStruntze** [comment]
Correct. My issue was fixed in my pr #14.

**Comment by Exho1** [comment]
Oh wow, that was silly of me then.

**Comment by Exho1** [comment]
FINALLY fixed, this issue was deeper than I thought and I had to get back into the phone to fix it. The issues were two-fold:
1. The notification system was trying to open the phone app twice when you accepted the call
2. The phone's automatic call disconnect system was triggering when the app closed and creating the main menu again
