### ISSUE TITLE
Error regarding perhaps corrupt config files

### ISSUE THREAD

**Issue by TheOnly8Z** [Exho1/gPhone#21]
`[gPhone] lua/gphone/cl_util.lua:548: attempt to call field 'msgC' (a nil value)
1. loadClientConfig - lua/gphone/cl_util.lua:548
2. buildPhone - lua/gphone/cl_phone.lua:40
3. unknown - lua/gphone/cl_phone.lua:24
`
I messed with some language files and code, and after reverting them, I keep getting this error. Deleted data/gphone and still no avail.

**Comment by Exho1** [comment]
This issue has occurred before because of a corrupt config file that needed to be regenerated. At first glance it would appear that the gPhone.msgC function in sh_util.lua (line 373) isn't being loaded on the client or isn't being loaded fast enough for the gPhone.buildPhone function.

Try running a little Lua to print the value attached to gPhone.msgC at different intervals to see if its being loaded on the client or not

**Comment by TheOnly8Z** [comment]
What should I run at which places? Should I add code to the serverside files to print?

**Comment by TheOnly8Z** [comment]
Also, the entire phone does not appear. This happens only to me on my server, other players were fine. How can I entirely reset the gphone settings?

**Comment by TheOnly8Z** [comment]
Complete deletion and reinstall of GMOD fixed this.
